version: "3.8"

services:
  app:
    container_name: app-dev
    image: node-mongo-app:v1
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001